### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/iBridges#258]
Add to docs:

- [x] data operations: switch off warnings --> #269 
- [x] metadata: metadata with keys starting with `org_` are ignored --> #269 
- [x] Go through all tutorials again. --> #260 
- [x] README Link to GUI --> #261 
- [x] README fix image --> #261 
- [ ] Go through all rst files again
