### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/iBridges#82]
- Sphinx documentation
- [x] Extend Setup instructions --> branch install-doc #147 
- [x] Give general examples for main functions 
- [x] Make sure the list of functionality is complete
- [x] Point to tutorials where appropriate
- [x] Integrate data sync tutorial --> branch sync-doc #148 
- [x] Integrate IrodsPath tutorial --> branch ipath-doc #149 
- [x] Add examples to docstrings
- [x] Single pages:
         - [ ] Session
         - [ ] Data transfers: upload, download, sync
         - [ ] Metadata
         - [x] iRODS Paths
         - [ ] Search
         - [x] CLI  

- Tutorials
- [x] Rename `Quickstart` to `Manual`
- [x] Create a real `Quickstart`
- [x] Wording in tutorials
- [x] Data sync --> move parts to Work with data tutorial
- [x] Update iRODS paths, needs to be first tutorial --> #165

**Comment by DorienHuijser** [comment]
Does this issue also include creating tutorials for the CLI? The tutorials (using Python) are way more elaborate than the README information about the CLI. But I assume that the same functionality is present in the CLI compared to the Python way?

**Comment by chStaiger** [comment]
> Does this issue also include creating tutorials for the CLI? The tutorials (using Python) are way more elaborate than the README information about the CLI. But I assume that the same functionality is present in the CLI compared to the Python way?

We will add a more elaborate section for the CLI on ReadTheDocs. However, they will not be as rich as the tutorials. The CLI is also more constraint in its functionality.
